### ISSUE TITLE
Getting Perfect in Special Stage kills music

### ISSUE THREAD

**Issue by MainMemory** [flamewing/flamedriver#6]
I've installed the Flamedriver in my hack, and when I get a Perfect in the Special Stage, instead of playing the sound effect, the music abruptly stops. Sound effects continue playing however, and the music comes back when it plays a new track. I tested your disassembly with the driver and it doesn't happen there.
[Example video](https://youtu.be/0gqVBzwgKts)

**Comment by marzojr** [comment]
The issue is that I decided to split music and sfx queues in Flamedriver, and S&K is horribly inconsistent on using music/sfx functions. The perfect jingle is actually a sfx, but it uses the music function (Play_Sound) instead of the sfx function (Play_Sound_2). Please see [this commit](https://github.com/flamewing/skdisasm/commit/49433a476235441bc4eb84aae6e3e8960eedc8bb) for the changes needed to fix S3&K.

**Comment by flamewing** [comment]
The issue is that I decided to split music and sfx queues in Flamedriver, and S&K is horribly inconsistent on using music/sfx functions. The perfect jingle is actually a sfx, but it uses the music function (Play_Sound) instead of the sfx function (Play_Sound_2). Please see [this commit](https://github.com/flamewing/skdisasm/commit/49433a476235441bc4eb84aae6e3e8960eedc8bb) for the changes needed to fix S3&K.

**Comment by MainMemory** [comment]
Okay, thank you.
